# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7IAEbtjsy8VMx44_e-CH1M-hRnigBgz
"""

import sys
import numpy as np
import streamlit as st
import pandas as pd
import joblib

# -----------------------------
# Compatibility shim
# -----------------------------
# The model was pickled with numpy 2.x, which renamed numpy.core to
# numpy._core internally. Older numpy versions (<2.0) don't have this
# module, so joblib.load() fails with "ModuleNotFoundError: No module
# named 'numpy._core'". Only patch this in when it's actually missing —
# on numpy>=2.0 the real numpy._core already exists and force-aliasing
# it to numpy.core breaks other imports (e.g. numpy.strings).
if "numpy._core" not in sys.modules:
    try:
        import numpy._core  # noqa: F401  (already present on numpy>=2.0)
    except ImportError:
        import numpy.core as core
        sys.modules["numpy._core"] = core

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="Software Release Risk Prediction",
    page_icon="🚀",
    layout="wide"
)

# -----------------------------
# Load Model
# -----------------------------
model = joblib.load("release_risk_model.pkl")
label_encoder = joblib.load("label_encoder.pkl")

# -----------------------------
# Title
# -----------------------------
st.title("🚀 Intelligent Software Release Risk Prediction System")

st.write("""
Predict the **risk level** of a software release using Machine Learning.
""")

st.markdown("---")

# -----------------------------
# Sidebar Inputs
# -----------------------------
st.sidebar.header("Enter Software Release Details")

commits = st.sidebar.number_input("Commits", 0, 1000, 150)

bugs = st.sidebar.number_input("Bugs Reported", 0, 100, 10)

critical = st.sidebar.number_input("Critical Bugs", 0, 20, 2)

coverage = st.sidebar.slider("Test Coverage (%)", 0.0, 100.0, 85.0)

failed = st.sidebar.number_input("Failed Test Cases", 0, 100, 5)

churn = st.sidebar.number_input("Code Churn", 0, 20000, 2500)

complexity = st.sidebar.number_input("Cyclomatic Complexity", 1, 100, 15)

files = st.sidebar.number_input("Files Changed", 1, 300, 30)

experience = st.sidebar.slider("Developer Experience (Years)", 0.0, 20.0, 5.0)

security = st.sidebar.number_input("Security Vulnerabilities", 0, 20, 1)

build = st.sidebar.number_input("Build Time (Minutes)", 1, 120, 20)

deployment = st.sidebar.number_input("Deployment Frequency", 1, 30, 6)

# -----------------------------
# Prediction Data
# -----------------------------
input_data = pd.DataFrame({
    "Commits":[commits],
    "Bugs_Reported":[bugs],
    "Critical_Bugs":[critical],
    "Test_Coverage":[coverage],
    "Failed_Test_Cases":[failed],
    "Code_Churn":[churn],
    "Cyclomatic_Complexity":[complexity],
    "Files_Changed":[files],
    "Developer_Experience":[experience],
    "Security_Vulnerabilities":[security],
    "Build_Time_Minutes":[build],
    "Deployment_Frequency":[deployment]
})

# -----------------------------
# Display Input
# -----------------------------
st.subheader("Input Data")

st.dataframe(input_data)

# -----------------------------
# Prediction
# -----------------------------
if st.button("Predict Risk"):

    prediction = model.predict(input_data)

    prediction_label = label_encoder.inverse_transform(prediction)[0]

    probability = model.predict_proba(input_data)

    confidence = probability.max() * 100

    st.markdown("---")

    st.header("Prediction Result")

    if prediction_label == "Low":
        st.success(f"✅ Release Risk : {prediction_label}")

    elif prediction_label == "Medium":
        st.warning(f"⚠️ Release Risk : {prediction_label}")

    else:
        st.error(f"🚨 Release Risk : {prediction_label}")

    st.write(f"### Confidence : {confidence:.2f}%")

    st.markdown("---")

    st.subheader("Probability of Each Risk Level")

    prob_df = pd.DataFrame({
        "Risk Level": label_encoder.classes_,
        "Probability (%)": probability[0] * 100
    })

    st.dataframe(prob_df)

    st.bar_chart(
        prob_df.set_index("Risk Level")
    )

    st.markdown("---")

    st.subheader("Recommendation")

    if prediction_label == "Low":

        st.success("""
        ✔ Ready for Deployment

        • Release is stable

        • Testing coverage is good

        • Proceed with deployment
        """)

    elif prediction_label == "Medium":

        st.warning("""
        Review before Deployment

        • Verify failed test cases

        • Improve test coverage

        • Review critical bugs
        """)

    else:

        st.error("""
        High Risk Release

        • Delay deployment

        • Fix critical bugs

        • Resolve security vulnerabilities

        • Increase testing coverage

        • Rebuild before release
        """)
